/**
 * Set 18 static data schemas (v1).
 *
 * These mirror `data/tft/set18/*.json` (generated by
 * `scripts/build-set18-data.mjs` from Riot's Data Dragon). `id` values are
 * the locale-independent `apiName`s, so ids stay stable across locales while
 * `name` / `description` are zh-CN.
 */

export const CHAMPION_COSTS = [1, 2, 3, 4, 5] as const;
export type ChampionCost = (typeof CHAMPION_COSTS)[number];

export interface ChampionData {
  id: string;
  name: string;
  cost: ChampionCost;
  /** Trait ids — must exist in `traits.json` of the same set. */
  traits: string[];
  set: number;
  role?: string;
  stats?: {
    hp: number;
    attack: number;
    armor: number;
    magicResist: number;
    attackSpeed: number;
    range: number;
    critChance: number;
    critMultiplier: number;
    initialMana: number;
  };
  ability?: { name: string; description: string };
  /** CommunityDragon asset path (`.tex`), not a bundled image. */
  icon?: string;
}

export interface TraitData {
  id: string;
  name: string;
  set: number;
  /** Published effect tiers (min-unit thresholds). May be empty. */
  breakpoints: number[];
  description: string;
  icon?: string;
}

export const ITEM_CATEGORIES = [
  "component",
  "completed",
  "radiant",
  "artifact",
  "support",
  "emblem",
  "other",
] as const;
export type ItemCategory = (typeof ITEM_CATEGORIES)[number];

export interface ItemData {
  id: string;
  name: string;
  category: ItemCategory;
  set: number;
  description: string;
  /** For completed items: the two component ids. */
  composition?: string[];
  icon?: string;
}

export interface AugmentData {
  id: string;
  name: string;
  set: number;
  description: string;
  icon?: string;
}

export interface TftDataManifest {
  set: number;
  name: string;
  /** e.g. `18.3` — the game patch the snapshot was cut from. */
  version: string;
  locale: string;
  schemaVersion: number;
  dataVersion: string;
  source: {
    name: string;
    url: string;
    sha256: string;
    retrievedAt: string;
    notes: string[];
  };
  generatedAt: string;
  counts?: { champions: number; traits: number; items: number; augments: number };
}

/** Everything for one set, in one object. */
export interface TftDataSnapshot {
  manifest: TftDataManifest;
  champions: ChampionData[];
  traits: TraitData[];
  items: ItemData[];
  augments: AugmentData[];
}
